version: '3'
services:
  app:
      build: .
      container_name: green-team-container
      ports:
        - "8080:8080"
      volumes:
        - green-team-data:/app
      environment:
        - SPRING_PROFILES_ACTIVE=dev
      restart: unless-stopped


 
volumes:
  green-team-data:
    driver: local
